version: '3.6'

services:
  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-master-db:/data/db

  redis-slave:
    image: redis
    container_name: redis-slave
    command: redis-server --slaveof redis-master 6379 --masterauth admin --requirepass admin
    depends_on:
      - redis-master
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-slave-db:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "9000:9000"
    env_file: configuration.env
    working_dir: /var/www
    volumes:
      - ./php:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

volumes:
  redis-master-db: {}
  redis-slave-db: {}